# Generated by Django 3.0.7 on 2020-10-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sightings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longtitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('uniqueId', models.CharField(max_length=100)),
                ('shift', models.CharField(choices=[('pm', 'PM'), ('am', 'AM')], max_length=100)),
                ('date', models.DateField()),
                ('age', models.CharField(choices=[('adult', 'Adult'), ('juvenile', 'Juvenile')], max_length=100)),
            ],
        ),
    ]
