# Generated by Django 3.0.7 on 2020-10-16 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sightings',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
